package model.entities.presents;

import javafx.util.Pair;
import model.entities.present_containers.Box;
import model.entities.present_items.IPresentItem;
import model.entities.present_items.Sweety;

import java.util.*;

/**
 * Created by Yuliia Tesliuk on 11/01/2018
 */
public class AutoGeneratedPresent extends Present<AutoGeneratedPresent,IPresentItem> {


    public AutoGeneratedPresent(int weight){
        this.container = new Box(weight);
    }

    @Override
    public AutoGeneratedPresent createPresent(List<IPresentItem> presentItems) {
        Random random = new Random();
        int nextItem;
        do{
            nextItem = random.nextInt(presentItems.size());
        }
        while(addToPresent(presentItems.get(nextItem), 1));

        return this;
    }

}
