package controller.servlets;

import controller.Util;
import model.entities.present_items.IPresentItem;
import model.entities.present_items.Sweety;
import model.entities.presents.AutoGeneratedPresent;
import model.entities.presents.CustomPresent;
import model.jdbc.DBConnection;
import model.jdbc.PresentItemDAO;
import model.jdbc.SweetyDAO;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.OptionalInt;
import java.util.stream.Collectors;

/**
 * Created by Yuliia Tesliuk on 11/05/2018
 */
@WebServlet("/constructor")
public class ConstructorServlet extends HttpServlet {
    private DBConnection dbConnection = new DBConnection();
    private PresentItemDAO<Sweety, String> itemDAO;
    private List<IPresentItem> sweeties;
    private CustomPresent present;

    @Override
    public void init() throws ServletException {
        itemDAO = new SweetyDAO(dbConnection.getConnection());
        sweeties = itemDAO.readAll().stream().map(x -> (IPresentItem) x).collect(Collectors.toList());
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        present = new CustomPresent();
        req.setAttribute("sweeties",sweeties);
        req.getRequestDispatcher("/WEB-INF/view/constructor.jsp").forward(req, resp);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        req.setCharacterEncoding("UTF8");

        final int minSugar = Util.toInteger(req.getParameter("minSugar"),0);
        final int maxSugar = Util.toInteger(req.getParameter("maxSugar"),Integer.MAX_VALUE);
        final int minWeight = Util.toInteger(req.getParameter("minWeight"),0);
        final int maxWeight = Util.toInteger(req.getParameter("maxWeight"),Integer.MAX_VALUE);
        final int minPrice = Util.toInteger(req.getParameter("minPrice"),0);
        final int maxPrice = Util.toInteger(req.getParameter("maxPrice"),Integer.MAX_VALUE);
        List<IPresentItem> filteredPresent = sweeties
                .stream()
                .filter(x -> (Util.isWithinBounds(x.getSugarContent(),minSugar,maxSugar) &&
                        Util.isWithinBounds(x.getWeight(),minWeight,maxWeight) &&
                        Util.isWithinBounds(x.getPrice(),minPrice,maxPrice)))
                .collect(Collectors.toList());


        req.setAttribute("sweeties", filteredPresent);
        req.getRequestDispatcher("/WEB-INF/view/constructor.jsp").forward(req, resp);

    }
}


