package controller.servlets;

import controller.util.Util;
import model.entities.present_items.*;
import model.entities.presents.*;
import model.jdbc.*;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.*;
import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Created by Yuliia Tesliuk on 11/05/2018
 */
@WebServlet("/present")
public class PresentPageServlet extends HttpServlet {
    private DBConnection dbConnection = new DBConnection();
    private PresentItemDAO<Sweety, String> itemDAO;
    private List<IPresentItem> sweeties;
    private AutoGeneratedPresent present;

    @Override
    public void init() throws ServletException {
        itemDAO = new SweetyDAO(dbConnection.getConnection());
        sweeties = itemDAO.readAll().stream().map(x -> (IPresentItem) x).collect(Collectors.toList());

    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        present = new AutoGeneratedPresent(Util.stringToInt(req.getParameter("presentWeight"), Present.DEFAULT_WEIGHT));
        present.createPresent(sweeties);
        req.setAttribute("sweeties", present.getPackagedPresent().entrySet());
        req.setAttribute("weight", present.getWeight());

        req.getRequestDispatcher("/WEB-INF/view/present.jsp").forward(req, resp);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        req.setCharacterEncoding("UTF8");

        String presentType = req.getParameter("sort");
        List<Map.Entry<IPresentItem, Integer>> sortedPresent = present.getPackagedPresent()
                .entrySet()
                .stream()
                .sorted(Comparator.comparing(x ->
                        (presentType.equals("sortByQTY")) ? x.getValue() :
                        (presentType.equals("sortByWeight")) ? x.getKey().getWeight() :
                        (presentType.equals("sortByPrice")) ? x.getKey().getPrice() :
                        (presentType.equals("sortBySugarContent")) ? (int)(x.getKey().getSugarContent() * 100)  :
                         x.getKey().getName().charAt(0),Comparator.reverseOrder()))
                .collect(Collectors.toList());


        req.setAttribute("sweeties", sortedPresent);
        req.setAttribute("weight", present.getWeight());
        req.getRequestDispatcher("/WEB-INF/view/present.jsp").forward(req, resp);

    }
}


