package controller.servlets;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Created by Yuliia Tesliuk on 11/06/2018
 */
@WebServlet("/redirect")
public class Redirect extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String presentType = req.getParameter("presentType");
        if (presentType.equals("AutoGeneratedPresent")){
            PresentPageServlet servlet = new PresentPageServlet();
            servlet.init();
            servlet.doGet(req,resp);
        } else {
            ConstructorServlet servlet = new ConstructorServlet();
            servlet.init();
            servlet.doGet(req,resp);
        }
    }
}
