package com.present.controller.reqhandler.commands;

import com.present.controller.util.NumberUtil;
import com.present.model.entities.present_items.IPresentItem;
import com.present.model.entities.presents.AutoGeneratedPresent;
import com.present.model.entities.presents.Present;

import javax.servlet.ServletException;
import java.io.IOException;
import java.util.List;

import static com.present.model.entities.presents.AutoGeneratedPresent.DEFAULT_MAX_WEIGHT;

/**
 * Created by Yuliia Tesliuk on 11/07/2018
 */
public class GeneratePresentCommand extends Command {
    private Present present;

    @Override
    public void process() throws ServletException, IOException {
        present = new AutoGeneratedPresent(NumberUtil.stringToInt(req.getParameter("presentWeight"), DEFAULT_MAX_WEIGHT));
        items = (List<IPresentItem>) session.getAttribute("items");

        present.createPresent(items);

        session.setAttribute("present",present);
        session.setAttribute("presentContent", present.getPackagedPresent().entrySet());
        session.setAttribute("weight", present.getWeight());
        session.setAttribute("price", present.getPrice());


        req.getRequestDispatcher("/WEB-INF/view/present.jsp").forward(req, resp);
    }
}