package com.present.model.entities.presents;

import com.present.controller.util.CollectionsUtil;
import com.present.model.entities.present_containers.Box;
import com.present.model.entities.present_items.IPresentItem;

import java.util.*;

/**
 * Created by Yuliia Tesliuk on 11/01/2018
 */
public class AutoGeneratedPresent extends Present {
    /**
     * Defines the default weight which is used for generating present item collection in case
     * if it is not explicitly defined using specific constructor
     */
    public static final int DEFAULT_MAX_WEIGHT = 500;


    public AutoGeneratedPresent(int weight){
        this.container = new Box(weight);
    }

    public AutoGeneratedPresent(){
        this(DEFAULT_MAX_WEIGHT);
    }

    /**
     * Fill in the present item collection by randomly picking not-null items from the provided list
     * until present container can't absorb next item
     * @param presentItems list of present items
     */
    @Override
    public void createPresent(List<IPresentItem> presentItems) {
        List<IPresentItem> filteredList = CollectionsUtil.nullFreeList(presentItems);

        if (filteredList.size() == 0) return;

        Random random = new Random();
        int nextItem;
        do{
            nextItem = random.nextInt(filteredList.size());
        }
        while(addToPresent(filteredList.get(nextItem), 1));
    }

    @Override
    public void createPresent(Map<IPresentItem, Integer> presentItems) {

    }

}
