package com.present.model.entities.presents;

import com.present.model.entities.present_containers.Box;
import com.present.model.entities.present_items.IPresentItem;

import java.util.*;

/**
 * Created by Yuliia Tesliuk on 11/01/2018
 */
public class AutoGeneratedPresent extends Present {


    public AutoGeneratedPresent(int weight){
        this.container = new Box(weight);
    }

    public AutoGeneratedPresent(){
        this(DEFAULT_WEIGHT);
    }

    @Override
    public void createPresent(List<IPresentItem> presentItems) {
        Random random = new Random();
        int nextItem;
        do{
            nextItem = random.nextInt(presentItems.size());
        }
        while(addToPresent(presentItems.get(nextItem), 1));
    }

    @Override
    public void createPresent(Map<IPresentItem, Integer> presentItems) {

    }

}
