package com.present.controller.servlets.commands;

import com.present.controller.util.Util;
import com.present.model.entities.present_items.IPresentItem;
import com.present.model.entities.presents.AutoGeneratedPresent;
import com.present.model.entities.presents.Present;

import javax.servlet.ServletException;
import java.io.IOException;
import java.util.List;

/**
 * Created by Yuliia Tesliuk on 11/07/2018
 */
public class GeneratePresentCommand extends Command {
    private Present present;

    @Override
    public void process() throws ServletException, IOException {
        present = new AutoGeneratedPresent(Util.stringToInt(req.getParameter("presentWeight"), Present.DEFAULT_WEIGHT));
        sweeties = (List<IPresentItem>) session.getAttribute("sweeties");
        present.createPresent(sweeties);

        session.setAttribute("present",present);
        session.setAttribute("presentContent", present.getPackagedPresent().entrySet());
        req.setAttribute("weight", present.getWeight());

        req.getRequestDispatcher("/WEB-INF/view/present.jsp").forward(req, resp);
    }
}